import React from "react";
import { DollarSign, Clock, Zap, TrendingUp, ChevronRight } from "lucide-react";

export default function ProfitTab({
  financials,
  decisionQualityScore,
  sendCopilotQuery
}) {
  return (
    <div className="space-y-6 animate-[fadeIn_0.3s_ease-out_forwards]">
      <div>
        <h2 className="text-2xl font-bold font-display tracking-tight text-slate-900">Factory Profit Impact & ROI Dashboard</h2>
        <p className="text-slate-500 text-sm">Executive-level financial KPIs quantifying the business value generated by AI-assisted maintenance.</p>
      </div>

      {/* Financial KPI Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="glass-panel border border-slate-200 rounded-2xl p-5 flex items-center gap-4 relative overflow-hidden bg-white card-hover-lift">
          <div className="w-12 h-12 bg-emerald-50 border border-emerald-100 rounded-xl flex items-center justify-center text-emerald-600 shrink-0 status-glow-emerald">
            <DollarSign className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] text-slate-500 block font-mono uppercase tracking-widest">COST SAVED TODAY</span>
            <span className="text-2xl font-bold text-emerald-600 font-hud">&#x20B9;{financials.cost_saved.toLocaleString()}</span>
          </div>
          <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-500/5 rounded-full translate-x-8 -translate-y-8"></div>
        </div>

        <div className="glass-panel border border-slate-200 rounded-2xl p-5 flex items-center gap-4 relative overflow-hidden bg-white card-hover-lift">
          <div className="w-12 h-12 bg-slate-100 border border-slate-200 rounded-xl flex items-center justify-center text-slate-700 shrink-0">
            <Clock className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] text-slate-500 block font-mono uppercase tracking-widest">DOWNTIME PREVENTED</span>
            <span className="text-2xl font-bold text-slate-800 font-hud">{financials.downtime_prevented} <span className="text-xs text-slate-500 font-sans">HRS</span></span>
          </div>
        </div>

        <div className="glass-panel border border-slate-200 rounded-2xl p-5 flex items-center gap-4 relative overflow-hidden bg-white card-hover-lift">
          <div className="w-12 h-12 bg-slate-100 border border-slate-200 rounded-xl flex items-center justify-center text-slate-700 shrink-0">
            <Zap className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] text-slate-500 block font-mono uppercase tracking-widest">ENERGY COST SAVED</span>
            <span className="text-2xl font-bold text-slate-800 font-hud">&#x20B9;{(financials.energy_saved * 10).toLocaleString()}</span>
          </div>
        </div>

        <div className="glass-panel border border-slate-200 rounded-2xl p-5 flex items-center gap-4 relative overflow-hidden bg-white card-hover-lift">
          <div className="w-12 h-12 bg-slate-100 border border-slate-200 rounded-xl flex items-center justify-center text-slate-700 shrink-0">
            <TrendingUp className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] text-slate-500 block font-mono uppercase tracking-widest">RECOVERED CAPACITY</span>
            <span className="text-2xl font-bold text-slate-800 font-hud">{financials.hours_recovered} <span className="text-xs text-slate-500 font-sans">HRS</span></span>
          </div>
        </div>
      </div>

      {/* Advanced Decision Economy & ROM Card */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* ROM Breakdown */}
        <div className="lg:col-span-2 glass-panel border border-slate-200 bg-white rounded-2xl p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between border-b border-slate-150 pb-3 mb-4">
              <h3 className="font-bold text-sm uppercase tracking-wider font-display flex items-center gap-2 text-slate-800">
                <TrendingUp className="w-5 h-5 text-emerald-600" />
                AI Return on Maintenance (ROM) Analysis
              </h3>
              <span className="text-[10px] text-slate-500 font-mono tracking-widest">SHOWCASE: ROBOT ARM M3</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-slate-650 font-sans">
              <div className="space-y-3.5 flex flex-col justify-center">
                <div className="flex justify-between border-b border-slate-150 pb-2">
                  <span className="text-slate-500">Planned Service Cost:</span>
                  <span className="font-mono text-slate-800 font-semibold">&#x20B9;18,000</span>
                </div>
                <div className="flex justify-between border-b border-slate-150 pb-2">
                  <span className="text-slate-500">Estimated Failure Gearbox Cost:</span>
                  <span className="font-mono text-slate-800 font-semibold">&#x20B9;2,10,000</span>
                </div>
                <div className="flex justify-between border-b border-slate-150 pb-2 text-rose-600">
                  <span className="font-semibold">Expected Production Loss (6 hrs):</span>
                  <span className="font-mono font-bold">&#x20B9;4,80,000</span>
                </div>
              </div>

              <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl flex flex-col justify-center text-center space-y-1">
                <span className="text-slate-500 text-[10px] font-bold uppercase tracking-wider">ESTIMATED DECISION SAVINGS</span>
                <span className="text-3xl font-extrabold text-emerald-600 font-hud">&#x20B9;6,72,000</span>
                <span className="text-[10px] text-slate-500 font-mono">ROM Ratio: <strong className="text-slate-800 font-hud">3,733%</strong></span>
              </div>
            </div>
          </div>
          <div className="border-t border-slate-150 pt-3 mt-4 text-[10px] text-slate-500 font-mono italic">
            *ROM Analysis calculation = (Expected Failure Loss - Planned Maintenance Cost) / Planned Maintenance Cost.
          </div>
        </div>

        {/* Business ROI Engine Card */}
        <div className="glass-panel border border-slate-200 bg-white rounded-2xl p-6 flex flex-col justify-between">
          <div>
            <h3 className="font-bold text-sm uppercase tracking-wider font-display mb-2 text-slate-900">Edge Decision ROI Story</h3>
            <p className="text-xs text-slate-500 leading-relaxed mb-4 font-sans">
              Traditional maintenance acts as a cost center. EdgeTwin AI turns maintenance into a **direct profit driver** by preventing unplanned asset halts and minimizing Scope 2 electricity consumption overhead.
            </p>
            <div className="space-y-2.5 text-xs font-mono">
              <div className="flex justify-between text-slate-650"><span>ROI Today:</span><span className="font-bold text-emerald-600 font-hud">26.7x</span></div>
              <div className="flex justify-between text-slate-650"><span>Decision Quality:</span><span className="font-bold text-slate-800 font-hud">{decisionQualityScore}%</span></div>
            </div>
          </div>
          <button 
            onClick={() => sendCopilotQuery("Show our total savings today.")}
            className="w-full mt-6 bg-slate-50 border border-slate-200 hover:bg-slate-100 hover:text-slate-900 text-slate-700 py-2.5 rounded-lg font-semibold text-xs transition-all duration-150 active-press flex items-center justify-center gap-1"
          >
            Ask Copilot for ROM breakdown <ChevronRight className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Estimated Client ROI Projection Matrix */}
      <div className="glass-panel border border-slate-200 bg-white rounded-2xl p-6">
        <div className="flex items-center justify-between border-b border-slate-150 pb-3 mb-5">
          <div>
            <h3 className="font-bold text-sm uppercase tracking-wider font-display text-slate-900">Estimated Client ROI Projection Matrix</h3>
            <p className="text-[10px] text-slate-500 font-mono mt-0.5">Projected annual savings at enterprise scale — based on EdgeTwin AI's measured per-decision value.</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] uppercase tracking-wider text-slate-500 font-mono">Decision Quality</span>
            <span className="bg-slate-50 text-slate-800 px-2.5 py-1 rounded text-sm font-hud font-bold border border-slate-200">{decisionQualityScore}%</span>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[
            { label: "Small Factory", subtitle: "5–10 machines", machines: 8, decisions: 24, savings: "₹48 Lakh", color: "text-slate-800", border: "border-slate-200", bg: "bg-slate-50/50" },
            { label: "Medium Factory", subtitle: "15–25 machines", machines: 20, decisions: 60, savings: "₹2.4 Crore", color: "text-emerald-600", border: "border-emerald-200/60", bg: "bg-emerald-50/20" },
            { label: "Large Enterprise", subtitle: "50+ machines", machines: 50, decisions: 150, savings: "₹8.1 Crore", color: "text-[#0061FF]", border: "border-blue-200/60", bg: "bg-blue-50/20" },
          ].map(tier => (
            <div key={tier.label} className={`rounded-2xl border p-5 flex flex-col justify-between transition-all duration-300 hover:scale-[1.01] ${tier.bg} ${tier.border}`}>
              <div>
                <span className="text-[10px] text-slate-500 font-mono uppercase tracking-widest">{tier.subtitle}</span>
                <h4 className={`font-bold text-lg font-hud mt-1 ${tier.color}`}>{tier.label}</h4>
                <div className="mt-3 space-y-2 text-xs text-slate-650">
                  <div className="flex justify-between"><span className="text-slate-500">Monitored Assets:</span><span className="font-mono font-semibold text-slate-800">{tier.machines}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">AI Decisions / Year:</span><span className="font-mono font-semibold text-slate-800">{tier.decisions}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">Avg Saved / Decision:</span><span className="font-mono font-semibold text-slate-800">₹2,00,000</span></div>
                </div>
              </div>
              <div className="mt-4 pt-3 border-t border-slate-200/60">
                <span className="text-[10px] uppercase tracking-wider text-slate-500 font-mono block">Est. Annual Savings</span>
                <span className={`text-2xl font-hud font-bold ${tier.color}`}>{tier.savings}</span>
              </div>
            </div>
          ))}
        </div>
        <div className="mt-5 p-3 bg-slate-50 rounded-xl border border-slate-200 text-[11px] text-slate-600 font-mono flex items-start gap-2">
          <span className="text-emerald-600 shrink-0 font-bold">✓</span>
          <span>All projections are calculated using EdgeTwin AI's actual observed <strong className="text-slate-800">₹4,17,000 per-decision avoided loss</strong> (as demonstrated live in this session).</span>
        </div>
      </div>
    </div>
  );
}
